server:
  servlet:
    context-path: /

spring:
  thymeleaf:
    cache: false
  mvc:
    view:
      prefix: classpath:/templates/**
      suffix: .html
    static-path-pattern: /static/**


  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.32.128:3306/Hitachi?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    filters: stat,wall,log4j
#        　　dbcp2:
#          　　min-idle: 5
#          　　initial-size: 5
#          　　max-total: 5
#          　　max-wait-millis: 200


mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.hitachi.entity
  configuration:
    map-underscore-to-camel-case: true


#showSql
logging:
  level:
    com:
      example:
        hitachi:
          mapper : debug
